### PR TITLE
add windows support by updating dependency

### PR DESCRIPTION
**Pull request by fcakyon**
@mmeendez8 @igonro @cgiraldo thanks a lot for this awesome package!

pycocotools-fix package currently doesnt work on windows: https://github.com/junjuew/cocoapi/pull/4

official pycocotools package is constantly updated by the facebook research team: https://pypi.org/project/pycocotools/

by accepting this pr, pyodi package will be supported on windows.

### CODE REVIEW

**Comment by mmeendez8** [comment]
Hi @fcakyon!

Thanks for your PR :) I am gonna add a CI build to test pyodi installation on windows and merge this if everything works properly!

**Comment by mmeendez8** [comment]
I can see build is crashing with pycocotools-fix https://github.com/Gradiant/pyodi/runs/3348162090

Could you merge your branch with master to use latest workflow so we can check if everything works as expected?

**Comment by fcakyon** [comment]
@mmeendez8 you mean i should merge in my own fork?

**Comment by mmeendez8** [comment]
> @mmeendez8 you mean i should merge in my own fork?

Yes, this is a bit annoying https://github.community/t/updating-workflow-file-on-master-and-rerunning-an-action-still-shows-old-workflow-file/18507/10

You can merge your local branch with master and push, that should trigger the latest changes in the workflow

**Comment by mmeendez8** [comment]
@fcakyon I just merged it for you! Thanks again for this :)

**Review by mmeendez8 — APPROVED** [review]

**Pull request merged**
